// Datos de ejemplo para desarrollo local sin Firebase configurado

export const mockCategories = [
  { id: '1', name: 'Pendientes', slug: 'pendientes', description: 'Pendientes artesanales', image_url: null, position: 1, active: true },
  { id: '2', name: 'Colgantes', slug: 'colgantes', description: 'Colgantes artesanales', image_url: null, position: 2, active: true },
  { id: '3', name: 'Pulseras', slug: 'pulseras', description: 'Pulseras artesanales', image_url: null, position: 3, active: true },
  { id: '4', name: 'Anillos', slug: 'anillos', description: 'Anillos artesanales', image_url: null, position: 4, active: true },
];

export const mockProducts = [
  {
    id: '1',
    name: 'Pendientes Peces Turquesa',
    slug: 'pendientes-peces-turquesa',
    description: 'Pendientes artesanales con forma de pez en arcilla polimérica con vetas turquesa y detalles de pan de oro. Ganchos de oro laminado 14k. Ligeros, únicos e irrepetibles — cada par es una pieza exclusiva hecha a mano.',
    price: 22.00,
    compare_at_price: 28.00,
    category_id: '1',
    categories: { name: 'Pendientes', slug: 'pendientes' },
    stock: 3,
    weight_grams: 12,
    images: [
      '/images/products/peces-turquesa-card-1.jpg',
      '/images/products/peces-turquesa-card-2.jpg',
      '/images/products/peces-turquesa-card-3.jpg',
      '/images/products/peces-turquesa-macro-1.jpg',
      '/images/products/peces-turquesa-modelo-1.jpg',
      '/images/products/peces-turquesa-modelo-3.jpg',
      '/images/products/peces-turquesa-lifestyle-4.jpg',
    ],
    tags: ['arcilla', 'pendientes', 'peces', 'turquesa', 'pan de oro'],
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Pendientes Peces Bicolor',
    slug: 'pendientes-peces-bicolor',
    description: 'Pendientes artesanales con forma de pez en arcilla polimérica bicolor turquesa y blanco moteado. Ganchos dorados. Pieza única hecha a mano.',
    price: 20.00,
    compare_at_price: null,
    category_id: '1',
    categories: { name: 'Pendientes', slug: 'pendientes' },
    stock: 4,
    weight_grams: 12,
    images: [
      '/images/products/peces-bicolor-card-1.jpg',
      '/images/products/peces-bicolor-flatlay-1.jpg',
    ],
    tags: ['arcilla', 'pendientes', 'peces', 'bicolor'],
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Pendientes Peces Remolino',
    slug: 'pendientes-peces-remolino',
    description: 'Pendientes artesanales con forma de pez en arcilla polimérica con efecto remolino turquesa y arena. Ganchos dorados. Cada par es único e irrepetible.',
    price: 22.00,
    compare_at_price: null,
    category_id: '1',
    categories: { name: 'Pendientes', slug: 'pendientes' },
    stock: 2,
    weight_grams: 12,
    images: [
      '/images/products/peces-remolino-modelo-1.jpg',
      '/images/products/peces-remolino-modelo-2.jpg',
    ],
    tags: ['arcilla', 'pendientes', 'peces', 'remolino', 'turquesa'],
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Pendientes Redondos Rojo Arena',
    slug: 'pendientes-redondos-rojo-arena',
    description: 'Pendientes de botón redondos en arcilla polimérica bicolor rojo y arena con purpurina. Ligeros y elegantes, perfectos para diario.',
    price: 16.00,
    compare_at_price: null,
    category_id: '1',
    categories: { name: 'Pendientes', slug: 'pendientes' },
    stock: 5,
    weight_grams: 8,
    images: [
      '/images/products/redondos-rojo-arena-lifestyle-1.jpg',
      '/images/products/redondos-rojo-arena-lifestyle-2.jpg',
    ],
    tags: ['arcilla', 'pendientes', 'redondos', 'rojo', 'arena'],
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Pendientes Redondos Verde Pan de Plata',
    slug: 'pendientes-redondos-verde-plata',
    description: 'Pendientes de botón redondos en arcilla polimérica verde con detalles de pan de plata. Acabado artesanal único.',
    price: 18.00,
    compare_at_price: null,
    category_id: '1',
    categories: { name: 'Pendientes', slug: 'pendientes' },
    stock: 3,
    weight_grams: 8,
    images: [
      '/images/products/redondos-verde-plata-lifestyle-1.jpg',
    ],
    tags: ['arcilla', 'pendientes', 'redondos', 'verde', 'pan de plata'],
    active: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Pendientes Cuadrados Púrpura Resina',
    slug: 'pendientes-cuadrados-purpura',
    description: 'Pendientes cuadrados en resina epoxy con efecto púrpura iridiscente y detalles dorados. Pieza única con acabado brillante.',
    price: 24.00,
    compare_at_price: null,
    category_id: '1',
    categories: { name: 'Pendientes', slug: 'pendientes' },
    stock: 2,
    weight_grams: 10,
    images: [
      '/images/products/cuadrados-purpura-modelo-1.jpg',
      '/images/products/cuadrados-purpura-flatlay-1.jpg',
    ],
    tags: ['resina', 'pendientes', 'cuadrados', 'purpura'],
    active: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
];

export const mockShippingRates = [
  { id: 'rate1', carrier: 'Correos', name: 'Estándar', description: '', rate: 3.50, estimated_days: '3-5 días hábiles', free_from_amount: 50 },
  { id: 'rate2', carrier: 'MRW', name: 'Express 24h', description: '', rate: 6.90, estimated_days: '1 día hábil', free_from_amount: null },
];
